### ISSUE TITLE
no bold characters

### ISSUE THREAD

**Issue by mmonaco** [kmscon/kmscon#55]
I've been putting off asking about this because the answer is probably obvious or something stupid that I'm missing.

When I'm in kmscon, I don't get bold characters. For example, notice and error messages from journalctl are not bold. Also, with lsblk and findmnt I do get the unicode line drawing characters, but they're the thinner alternatives.

**Comment by ruby-R53** [comment]
this is not working for me here··· i'm using Unifont at size 12 and bold characters render normally on my terminal emulator, but not on kmscon

i wonder what's wrong, am i missing something or is there actually a problem with how it render this font in particular?
