### ISSUE TITLE
Adding support to specify cursor blinking type and size

### ISSUE THREAD

**Issue by vkravets** [kmscon/kmscon#57]
There no fealing that I working in the real console. Cursor in blinking =)

Will great if there will options related to cursor (box size, blinking refresh rate and so on)

**Comment by andmarti1424** [comment]
Is there a way to change the default cursor in kmscon to blinking one? Thanks.

**Comment by andmarti1424** [comment]
Is there a way to change the default cursor in kmscon to blinking one? Thanks.
