### ISSUE TITLE
Can't switch to VTx after login

### ISSUE THREAD

**Issue by thiagokokada** [kmscon/kmscon#88]
I am using Arch Linux with KDE 4.10 and KDM as my graphical login manager. I put systemd to auto-spawn kmsconvt@.service to the VT1-6 (like it's written on the Arch Wiki: https://wiki.archlinux.org/index.php/KMSCON) and everything works fine until I login on my KDE session using KDM (doesn't happen before I login, i.e. it works fine while I am on my KDM screen). After that, every time I try to change to a VT with an already running kmscon it just stays on a freeze screen (like a screenshot) of my KDE desktop. If I switch to a empty VT (with a not yet running kmscon or a VT that doesn't run kmscon by default like VT8), I can go to any of the VT already running kmscon without problem. I can go back to my KDE session too, so it seems it isn't a problem of really freezing kmscon, just the display buffer or something that isn't refreshing after the switching.

**Comment by yshui** [comment]
I can reproduce this problem with.

Switch from X -> empty vt, kmscon auto starts as works fine, switch from X -> vt where kmscon is already running, black screen.
